export const projectBackLogFilters = {
    projectId: 1,
    searchText: null,
    workGroupId: null,
    assignedPersonId: '',
    reportedPersonId: null,
    projectType: '',
    projectStatus: '',
    startDate: null,
    endDate: null,
    priority: null,
    pageNumber: 1,
    pageSize: 5,
    expression: 'title',
    isSortByAsc: true
}
export const AddProjectBackLogRequest = {
    employeeId: '1',
    projectId: '1',
    subProjectId: '',
    title: '',
    workGroupId: '1',
    workFlow: 5,
    priority: 'Medium',
    projectStatusId: 1,
    startDate: new Date(),
    endDate: new Date(),
    originalEstTime: 0,
    remainingEstTime: 0,
    assignedEmployeeId: '1',
    reportedEmployeeId: '1',
    releasedToProduction: false,
    rsi: 1,
    description: ''
}
export const EditProjectBackLogRequest = {
    projectWorkId: '',
    employeeId: '1',
    projectId: '1',
    subProjectId: null,
    title: '',
    workGroupId: '1',
    workFlow: 5,
    priority: 'Medium',
    projectStatusId: 0,
    startDate: new Date(),
    endDate: new Date(),
    originalEstTime: 0,
    assignedEmployeeId: '1',
    reportedEmployeeId: '',
    releasedToProduction: true,
    rsi: 1,
    description: null
}